# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'AppSubscription'
    KeyVaultName: 'raviservianappkv'
    SecretsFilter: 'dbpassword'
    RunAsPreJob: true
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AppSubscription'
    subscriptionId: 'd0f8a7ea-2fb9-44f3-830a-6e48ae4f735b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ServianAssignmentRG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'ARMTemplates/arm_azurepostgsql.json'
    csmParametersFile: 'ARMTemplates/arm_azurepostgsql.parameters.json'
    overrideParameters: '-administratorLoginPassword $(dbpassword)'
    deploymentMode: 'Incremental'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'AppSubscription'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az postgres  server firewall-rule create --resource-group ServianAssignmentRG --server ravixrca4postgresql -n AllowYourIp --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
      
      psql "host=ravixrca4postgresql.postgres.database.azure.com port=5432 dbname=postgres user=servianuser@ravixrca4postgresql password=$(dbpassword) sslmode=require" -t -c "CREATE ROLE servianappuser WITH LOGIN NOSUPERUSER INHERIT CREATEDB CREATEROLE NOREPLICATION PASSWORD '$(dbpassword)';GRANT azure_pg_admin TO servianappuser;"

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'AppSubscription'
    subscriptionId: 'd0f8a7ea-2fb9-44f3-830a-6e48ae4f735b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ServianAssignmentRG'
    location: 'Australia East'
    templateLocation: 'Linked artifact'
    csmFile: 'ARMTemplates/arm_appservice.json'
    csmParametersFile: 'ARMTemplates/arm_appservice.parameters.json'
    deploymentMode: 'Incremental'    


